root: true
extends:
  - prettier
  - plugin:react/recommended
parserOptions:
  sourceType: 'module'
  ecmaVersion: 2020
env:
  browser: true
  es6: true
  node: true
globals:
  inkdrop: true
rules:
  no-useless-escape: 0
  prefer-const: 2
  no-unused-vars:
    - 2
    - argsIgnorePattern: ^_
      varsIgnorePattern: ^_
